#!/usr/bin/env python3

from sys import stdout
from argparse import ArgumentParser
from socket import socket
from time import sleep

parser = ArgumentParser()
parser.add_argument(
    '--host', '-r', required=True,
    help='address to listen on'
)
parser.add_argument(
    '--port', '-p', type=int, required=True,
    help='port to listen on'
)
parser.add_argument(
    '--buffer-size', '-b', type=int, default=4096,
    help='how much data to process at a time'
)
args = parser.parse_args()

try:
    while True:
        with socket() as sock:
            while True:
                try:
                    sock.connect((args.host, args.port))
                    break
                except ConnectionRefusedError:
                    sleep(0.5)
            while (piece := sock.recv(args.buffer_size)):
                stdout.buffer.write(piece)
                stdout.buffer.flush()
except KeyboardInterrupt:
    pass
